"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { Menu, X } from "lucide-react";
import { nav } from "@/data/site";

export function Navbar() { const [open,setOpen]=useState(false); const [scrolled,setScrolled]=useState(false); const reduce=useReducedMotion(); useEffect(()=>{const onScroll=()=>setScrolled(scrollY>24); onScroll(); addEventListener("scroll",onScroll); return()=>removeEventListener("scroll",onScroll)},[]); return <header className={`fixed inset-x-0 top-0 z-50 transition-all duration-500 ${scrolled||open?"border-b border-brand-neutral bg-brand-cream/95 text-brand-black backdrop-blur":"text-white"}`}><div className="shell flex min-h-20 items-center justify-between py-3"><Link href="/" className="flex items-center py-2" aria-label="New Hong Kong home"><Image src={scrolled||open?"/logo-dark.png":"/logo-light.png"} alt="New Hong Kong Asian Food Bar" width={1000} height={180} priority className="h-auto w-[300px]"/></Link><nav className="hidden items-center gap-7 lg:flex" aria-label="Main navigation">{nav.map(i=><Link key={i.href} href={i.href} className="text-xs font-semibold uppercase tracking-wider hover:text-brand-red">{i.label}</Link>)}<Link href="/booking" className="rounded-full bg-brand-red px-5 py-3 text-xs font-bold uppercase tracking-wider text-white transition hover:bg-brand-red-dark">Book a Table</Link></nav><button type="button" onClick={()=>setOpen(!open)} className="grid h-11 w-11 place-items-center lg:hidden" aria-label={open?"Close navigation":"Open navigation"} aria-expanded={open}>{open?<X/>:<Menu/>}</button></div><AnimatePresence>{open&&<motion.div initial={reduce?false:{opacity:0,y:-15}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-15}} className="bg-brand-charcoal px-5 pb-8 pt-3 text-white lg:hidden"><nav className="flex flex-col gap-1" aria-label="Mobile navigation">{nav.map(i=><Link onClick={()=>setOpen(false)} key={i.href} href={i.href} className="border-b border-white/15 py-4 font-display text-3xl uppercase">{i.label}</Link>)}<Link onClick={()=>setOpen(false)} href="/booking" className="mt-5 rounded-full bg-brand-red px-5 py-4 text-center text-xs font-bold uppercase tracking-wider">Book a Table</Link></nav></motion.div>}</AnimatePresence></header> }
